### ISSUE TITLE
/t2i & /i2t commands appear non-functioning

### ISSUE THREAD

**Issue by mrowwy** [gumblex/orizonhub#2]
I've uncommented the commands in commands/control.py but I'm seeing this issue:

2017-11-18 10:41:29,598 [E:handler] Failed to execute: Request(cmd='t2i', expr='', kwargs={'msg': Message(id=None, protocol='telegrambot', pid=80528, src=User(id=None, protocol='telegram', type=<UserType.user: 1>, pid=84640731, username='mrowwy', first_name='mrowwy', last_name=None, alias=None), chat=User(id=None, protocol='telegram', type=<UserType.group: 2>, pid=-1001061224056, username=None, first_name='Test Group', last_name=None, alias=None), text='/t2i', media={'entities': [{'length': 4, 'type': 'bot_command', 'offset': 0}]}, time=1511030647, fwd_src=None, fwd_time=None, reply=None, mtype='group', alttext=None)})
Traceback (most recent call last):
  File "/home/user/orizonhub-simple/orizonhub/consumer.py", line 135, in dispatch
    r = c.func(req.expr, **req.kwargs)
  File "/home/user/orizonhub-simple/orizonhub/command/control.py", line 23, in cmd_t2i
    if expr == 'off' or CFG.get('t2i'):
NameError: name 'CFG' is not defined

I'm coming from an old version of relay.py and use the commands frequently. Thoughts?

**Comment by gumblex** [comment]
Oh I left that unimplemented since I myself no longer use that. I will see how to implement this.

**Comment by mrowwy** [comment]
I noticed -master doesn't throw the same errors, so maybe there's compounding issues depending on branch. Either way, that would be amazing :) thanks for what you do!

**Comment by gumblex** [comment]
I've added this. No admin list support though.
